# Documentation for how to configure goreleaser can be found at http://goreleaser.com
project_name: kyma
release:
  github:
    owner: kyma-project
    name: cli
  prerelease: auto
before:
  hooks:
    - make resolve
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  - KYMA_VERSION=1.2.0-rc1
  ldflags: -X github.com/kyma-project/cli/pkg/kyma/cmd.Version={{.Version}} -X github.com/kyma-project/cli/pkg/kyma/cmd/install.DefaultKymaVersion={{.Env.KYMA_VERSION}}
  main: ./cmd/kyma/
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
