required = [
  "golang.org/x/lint/golint",
]

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/briandowns/spinner"
  version = "1.6.0"

[[constraint]]
  name = "github.com/fsouza/go-dockerclient"
  version = "1.4.1"

# one of our dependencies (gopkg.in/inf.v0@v0.9.1) is trying to download docker 1.13 and it is incompatible with go-dockerclient
# This override fixes that.
# We can't use any verison because docker stopped doing releases on 2017, but they keep committing to master.

[[override]]
  name = "github.com/docker/docker"
  revision = "ae0c0cdffdf24c2424abaf8d67fe0e0d27c06ccd"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.5"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.3"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.3"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[override]]
  name = "github.com/russross/blackfriday"
  version = "1.4.0"  

[[constraint]]
  name = "github.com/daviddengcn/go-colortext"
  revision = "186a3d44e9200d7eb331356ca4864f52708e1399"