apiVersion: v1
kind: Namespace
metadata:
  name: kyma-installer
  labels:
    istio-injection: disabled
    kyma-project.io/installation: ""
---
apiVersion: v1
kind: LimitRange
metadata:
  name: kyma-default
  namespace: kyma-installer
  labels:
    kyma-project.io/installation: ""
spec:
  limits:
  - max:
      memory: 1024Mi # Maximum memory that a container can request
    default:
      # If a container does not specify memory limit, this default value will be applied.
      # If a container tries to allocate more memory, container will be OOM killed.
      memory: 96Mi
    defaultRequest:
      # If a container does not specify memory request, this default value will be applied.
      # The scheduler considers this value when scheduling a container to a node.
      # If a node has not enough memory, such pod will not be created.
      memory: 32Mi
    type: Container
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: installations.installer.kyma-project.io
  labels:
    kyma-project.io/installation: ""
spec:
  group: installer.kyma-project.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Installation
    singular: installation
    plural: installations
    shortNames: ['installation']
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: releases.release.kyma-project.io
  labels:
    kyma-project.io/installation: ""
spec:
  group: release.kyma-project.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Release
    singular: release
    plural: releases
    shortNames: ['release']
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kyma-installer
  namespace: kyma-installer
  labels:
    kyma-project.io/installation: ""
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kyma-installer
  namespace: kyma-installer
  labels:
    kyma-project.io/installation: ""
spec:
  template:
    metadata:
      labels:
        name: kyma-installer
    spec:
      serviceAccountName: kyma-installer
      containers:
      - name: kyma-installer-container
        image: eu.gcr.io/kyma-project/kyma-installer:0.8.2
        imagePullPolicy: IfNotPresent
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kyma-installer-reader
  labels:
    kyma-project.io/installation: ""
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kyma-installer
  labels:
    kyma-project.io/installation: ""
subjects:
- kind: ServiceAccount
  name: kyma-installer
  namespace: kyma-installer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyma-installer-reader
---
apiVersion: "installer.kyma-project.io/v1alpha1"
kind: Installation
metadata:
  name: kyma-installation
  labels:
    kyma-project.io/installation: ""
  finalizers:
    - finalizer.installer.kyma-project.io
spec:
  version: "0.0.1"
  url: ""
  components:
    - name: "cluster-essentials"
      namespace: "kyma-system"
    - name: "istio"
      namespace: "istio-system"
    - name: "knative"
      namespace: "istio-system" # KNative comes with namespaces hardcoded so this one is only for installer
    - name: "istio-kyma-patch"
      namespace: "istio-system"
    # - name: "prometheus-operator"
    # namespace: "kyma-system"
    - name: "dex"
      namespace: "kyma-system"
    - name: "service-catalog"
      namespace: "kyma-system"
    - name: "service-catalog-addons"
      namespace: "kyma-system"
    - name: "helm-broker"
      namespace: "kyma-system"
    - name: "nats-streaming"
      namespace: "natss"
    - name: "assetstore"
      namespace: "kyma-system"
    - name: "cms"
      namespace: "kyma-system"
    - name: "core"
      namespace: "kyma-system"
    - name: "event-bus"
      namespace: "kyma-system"
    - name: "application-connector-ingress"
      namespace: "kyma-system"
    - name: "application-connector"
      namespace: "kyma-integration"
    #- name: "ark"
    #  namespace: "heptio-ark"
    #- name: "logging"
    #  namespace: "kyma-system"
    #- name: "jaeger"
    #  namespace: "kyma-system"
    #- name: "monitoring"
    #  namespace: "kyma-system"
---
