apiVersion: rafter.kyma-project.io/v1beta1
kind: ClusterAssetGroup
metadata:
  labels:
    rafter.kyma-project.io/view-context: cli
    rafter.kyma-project.io/group-name: cli
    rafter.kyma-project.io/order: "1"
  name: overview
spec:
  displayName: "Kyma CLI"
  description: "Overall documentation for CLI"
  sources:
    - type: markdown
      name: docs
      mode: package
      filter: /docs/
